### ISSUE TITLE
conflict with react-native-firebase

### ISSUE THREAD

**Issue by AdelHamad** [tolu360/react-native-google-places#115]
Hello folks

when i install react-native-google-places aside with react-native-firebase
after compiling the app crashes right away

i got this from android studio logcat

03-10 14:37:33.751 32605-32631/? E/AndroidRuntime: FATAL EXCEPTION: Thread-4
                                                   Process: com.XXXX, PID: 32605
                                                   java.lang.AbstractMethodError: abstract method "com.google.android.gms.common.api.Api$zze com.google.android.gms.common.api.Api$zza.zza(android.content.Context, android.os.Looper, com.google.android.gms.common.internal.zzr, java.lang.Object, com.google.android.gms.common.api.GoogleApiClient$ConnectionCallbacks, com.google.android.gms.common.api.GoogleApiClient$OnConnectionFailedListener)"
                                                       at com.google.android.gms.common.api.GoogleApiClient$Builder.build(Unknown Source)
                                                       at com.arttitude360.reactnative.rngoogleplaces.RNGooglePlacesModule.buildGoogleApiClient(RNGooglePlacesModule.java:76)
                                                       at com.arttitude360.reactnative.rngoogleplaces.RNGooglePlacesModule.<init>(RNGooglePlacesModule.java:59)
                                                       at com.arttitude360.reactnative.rngoogleplaces.RNGooglePlacesPackage.createNativeModules(RNGooglePlacesPackage.java:29)
                                                       at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:106)
                                                       at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1171)
                                                       at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1141)
                                                       at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1083)
                                                       at com.facebook.react.ReactInstanceManager.access$900(ReactInstanceManager.java:113)
                                                       at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:920)
                                                       at java.lang.Thread.run(Thread.java:776)

any help would be appreciated

**Comment by fidanoskimkd** [comment]
Hey, I am experiencing the same error, are there any resolutions to this ?

**Comment by agrantham** [comment]
I am also having this same issue but I did not install react-native-firebase. Any resolution?

**Comment by AdelHamad** [comment]
i solved this by updating google play services version

    compile "com.google.android.gms:play-services-base:11.8.0"
    compile "com.google.firebase:firebase-core:11.8.0"
    compile "com.google.firebase:firebase-messaging:11.8.0"
    compile 'com.google.android.gms:play-services-places:11.8.0'
    compile 'com.google.android.gms:play-services-location:11.8.0'

**Comment by brspower** [comment]
Any news ?

**Comment by brspower** [comment]
`Depencencies : {
    ....
   implementation (project(':react-native-google-places')) {
        exclude group: 'com.google.android.gms', module: 'play-services-base'
        exclude group: 'com.google.android.gms', module: 'play-services-places'
        exclude group: 'com.google.android.gms', module: 'play-services-location'
    }
    implementation "com.google.android.gms:play-services-base:16.0.1"
    implementation 'com.google.android.gms:play-services-places:16.0.0'
    implementation 'com.google.android.gms:play-services-location:16.0.0'
}` 



This solved my problem btw
