### ISSUE TITLE
Android application not starting

### ISSUE THREAD

**Issue by jdrouet** [tolu360/react-native-google-places#80]
I installed this plugin, It works perfectly on ios, but on android it starts and crashes instantly.

<img width="289" alt="screen shot 2017-08-26 at 23 26 19" src="https://user-images.githubusercontent.com/6329508/29744860-0cb7079c-8ab6-11e7-9f80-e5ee72739e4c.png">

### The node versions I use
```
{
    "react-native": "^0.46.4",
    "react-native-datepicker": "^1.6.0",
    "react-native-fbsdk": "^0.6.0",
    "react-native-google-places": "^2.4.2",
    "react-native-image-picker": "^0.26.3",
    "react-native-invertible-flat-list": "^1.1.0",
    "react-native-linear-gradient": "^2.0.0",
    "react-native-onesignal": "^3.0.4",
    "react-native-side-menu": "^1.0.2",
    "react-native-splash-screen": "^2.1.0"
}
```

### Here is the my android/app/build.gradle
```
dependencies {
    compile project(':bugsnag-react-native')
    compile project(':react-native-onesignal')
    compile project(':react-native-image-picker')
    compile project(':react-native-fbsdk')
    compile project(':react-native-splash-screen')
    compile project(':react-native-linear-gradient')
    compile project(':react-native-google-places')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"  // From node_modules
    compile 'com.google.android.gms:play-services-base:10.2.4'
    compile 'com.google.android.gms:play-services-places:10.2.4'
    compile 'com.google.android.gms:play-services-location:10.2.4'
    compile 'com.google.maps.android:android-maps-utils:0.3.4'
}
```

### Here is the log I get when I start the application on android
```
08-26 23:16:14.065  1624  2023 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.adventurer/.MainActivity (has extras)} from uid 10009 on display 0
08-26 23:16:14.078  3643  3643 I art     : Not late-enabling -Xcheck:jni (already on)
08-26 23:16:14.087  1624  1635 I ActivityManager: Start proc 3643:com.adventurer/u0a60 for activity com.adventurer/.MainActivity
08-26 23:16:14.087  1624  1638 W BroadcastQueue: Permission Denial: broadcasting Intent { act=com.android.launcher3.action.LAUNCH flg=0x10 (has extras) } from com.android.launcher3 (pid=1995, uid=10009) requires com.google.android.launcher.permission.RECEIVE_LAUNCH_BROADCASTS due to receiver com.google.android.gms/.icing.proxy.ApplicationLauncherReceiver
08-26 23:16:14.087  1624  1638 W BroadcastQueue: Permission Denial: receiving Intent { act=com.android.launcher3.action.LAUNCH flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$GmsExternalReceiver requires com.android.launcher3.permission.RECEIVE_LAUNCH_BROADCASTS due to sender com.android.launcher3 (uid 10009)
08-26 23:16:14.087  1624  1638 W BroadcastQueue: Permission Denial: broadcasting Intent { act=com.android.launcher3.action.LAUNCH flg=0x10 (has extras) } from com.android.launcher3 (pid=1995, uid=10009) requires com.google.android.launcher.permission.RECEIVE_LAUNCH_BROADCASTS due to receiver com.google.android.googlequicksearchbox/com.google.android.search.core.icingsync.ApplicationLaunchReceiver
08-26 23:16:14.123  3643  3643 V fb-UnpackingSoSource: locked dso store /data/user/0/com.adventurer/lib-main
08-26 23:16:14.123  3643  3643 I fb-UnpackingSoSource: dso store is up-to-date: /data/user/0/com.adventurer/lib-main
08-26 23:16:14.123  3643  3643 V fb-UnpackingSoSource: releasing dso store lock for /data/user/0/com.adventurer/lib-main
08-26 23:16:14.190  1259  1664 D gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 8294400
08-26 23:16:14.219  1259  1339 E SurfaceFlinger: ro.sf.lcd_density must be defined as a build property
08-26 23:16:14.221  3643  3667 D OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
08-26 23:16:14.223  3643  3643 D         : HostConnection::get() New Host Connection established 0xae524a00, tid 3643
08-26 23:16:14.279  3643  3643 W         : Unrecognized GLES max version string in extensions: ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_dma_v1
08-26 23:16:14.284  1995  2147 D EGL_emulation: eglMakeCurrent: 0xae3d45a0: ver 2 0 (tinfo 0xae3d26a0)
08-26 23:16:14.285  1995  2147 E Surface : getSlotFromBufferLocked: unknown buffer: 0xaaa498c0
08-26 23:16:14.332  3643  3643 I art     : Thread[1,tid=3643,Native,Thread*=0xb4034500,peer=0x73efaf68,"main"] recursive attempt to load library "/data/app/com.adventurer-2/lib/x86/libfb.so"
08-26 23:16:14.344  3643  3678 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTGroupViewManager
08-26 23:16:14.345  3643  3678 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTGroupShadowNode
08-26 23:16:14.347  3643  3678 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTShapeViewManager
08-26 23:16:14.347  3643  3678 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTShapeShadowNode
08-26 23:16:14.348  3643  3678 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTTextViewManager
08-26 23:16:14.348  3643  3678 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTTextShadowNode
08-26 23:16:14.348  3643  3678 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.picker.ReactDialogPickerManager
08-26 23:16:14.350  3643  3678 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.uimanager.LayoutShadowNode
08-26 23:16:14.351  3643  3678 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.drawer.ReactDrawerLayoutManager
08-26 23:16:14.354  3643  3678 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.picker.ReactDropdownPickerManager
08-26 23:16:14.354  3643  3678 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.scroll.ReactHorizontalScrollViewManager
08-26 23:16:14.356  3643  3678 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.progressbar.ReactProgressBarViewManager
08-26 23:16:14.356  3643  3678 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.progressbar.ProgressBarShadowNode
08-26 23:16:14.357  3643  3678 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.scroll.ReactScrollViewManager
08-26 23:16:14.359  3643  3678 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.slider.ReactSliderManager
08-26 23:16:14.360  3643  3678 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.slider.ReactSliderManager$ReactSliderShadowNode
08-26 23:16:14.360  3643  3678 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.switchview.ReactSwitchManager
08-26 23:16:14.361  3643  3678 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.switchview.ReactSwitchManager$ReactSwitchShadowNode
08-26 23:16:14.362  3643  3678 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.toolbar.ReactToolbarManager
08-26 23:16:14.364  3643  3678 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.webview.ReactWebViewManager
08-26 23:16:14.364  3643  3678 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.swiperefresh.SwipeRefreshLayoutManager
08-26 23:16:14.365  3643  3678 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTSurfaceViewManager
08-26 23:16:14.365  3643  3678 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTSurfaceViewShadowNode
08-26 23:16:14.365  3643  3678 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.frescosupport.FrescoBasedReactTextInlineImageViewManager
08-26 23:16:14.366  3643  3678 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.frescosupport.FrescoBasedReactTextInlineImageShadowNode
08-26 23:16:14.366  3643  3678 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.image.ReactImageManager
08-26 23:16:14.367  3643  3678 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.modal.ReactModalHostManager
08-26 23:16:14.367  3643  3678 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.modal.ModalHostShadowNode
08-26 23:16:14.367  3643  3678 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactRawTextManager
08-26 23:16:14.368  3643  3678 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactTextShadowNode
08-26 23:16:14.369  3643  3678 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.textinput.ReactTextInputManager
08-26 23:16:14.372  3643  3678 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.textinput.ReactTextInputShadowNode
08-26 23:16:14.372  3643  3678 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactTextViewManager
08-26 23:16:14.372  3643  3678 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.view.ReactViewManager
08-26 23:16:14.373  3643  3678 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.viewpager.ReactViewPagerManager
08-26 23:16:14.375  3643  3678 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactVirtualTextViewManager
08-26 23:16:14.375  3643  3678 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.reactnative.androidsdk.FBLikeViewManager
08-26 23:16:14.376  3643  3678 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.reactnative.androidsdk.FBLoginButtonManager
08-26 23:16:14.376  3643  3678 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.reactnative.androidsdk.FBSendButtonManager
08-26 23:16:14.377  3643  3678 W art     : Before Android 4.1, method boolean com.facebook.share.widget.ShareButtonBase.canShare() would have incorrectly overridden the package-private method in android.widget.TextView
08-26 23:16:14.377  3643  3678 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.reactnative.androidsdk.FBShareButtonManager
08-26 23:16:14.377  3643  3678 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.BV.LinearGradient.LinearGradientManager
08-26 23:16:14.383  3643  3678 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.places.internal.zzh>
08-26 23:16:14.383  3643  3678 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.places.internal.zzh>
08-26 23:16:14.383  3643  3678 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.places.internal.zzh>
08-26 23:16:14.383  3643  3678 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.places.internal.zzh>
08-26 23:16:14.383  3643  3678 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.places.internal.zzn>
08-26 23:16:14.384  3643  3678 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.places.internal.zzn>
08-26 23:16:14.384  3643  3678 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.places.internal.zzn>
08-26 23:16:14.384  3643  3678 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.places.internal.zzn>
08-26 23:16:14.384  3643  3678 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.places.zzo$zzb>
08-26 23:16:14.384  3643  3678 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.places.zzo$zzb>
08-26 23:16:14.384  3643  3678 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.places.zzo$zzc>
08-26 23:16:14.384  3643  3678 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.places.zzo$zzc>
08-26 23:16:14.384  3643  3678 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.places.internal.zzg$1>
08-26 23:16:14.384  3643  3678 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.places.internal.zzg$1>
08-26 23:16:14.385  3643  3678 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.places.zzo$zzb>
08-26 23:16:14.385  3643  3678 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.places.zzo$zza>
08-26 23:16:14.385  3643  3678 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.places.zzo$zza>
08-26 23:16:14.385  3643  3678 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.places.internal.zzg$4>
08-26 23:16:14.385  3643  3678 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.places.internal.zzg$4>
08-26 23:16:14.385  3643  3678 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.places.zzo$zzb>
08-26 23:16:14.385  3643  3678 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.places.zzh$zzb>
08-26 23:16:14.385  3643  3678 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.places.zzh$zzb>
08-26 23:16:14.385  3643  3678 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.places.internal.zzg$2>
08-26 23:16:14.385  3643  3678 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.places.internal.zzg$2>
08-26 23:16:14.385  3643  3678 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.places.zzo$zzb>
08-26 23:16:14.385  3643  3678 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.places.zzo$zzd>
08-26 23:16:14.385  3643  3678 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.places.zzo$zzd>
08-26 23:16:14.385  3643  3678 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.places.internal.zzm$1>
08-26 23:16:14.385  3643  3678 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.places.internal.zzm$1>
08-26 23:16:14.386  3643  3678 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.places.zzo$zzb>
08-26 23:16:14.386  3643  3678 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.places.zzo$zzf>
08-26 23:16:14.386  3643  3678 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.places.zzo$zzf>
08-26 23:16:14.386  3643  3678 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.places.internal.zzm$2>
08-26 23:16:14.386  3643  3678 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.places.internal.zzm$2>
08-26 23:16:14.386  3643  3678 E AndroidRuntime: FATAL EXCEPTION: Thread-196
08-26 23:16:14.386  3643  3678 E AndroidRuntime: Process: com.adventurer, PID: 3643
08-26 23:16:14.386  3643  3678 E AndroidRuntime: java.lang.AbstractMethodError: abstract method "com.google.android.gms.common.api.Api$zze com.google.android.gms.common.api.Api$zza.zza(android.content.Context, android.os.Looper, com.google.android.gms.common.internal.zzq, java.lang.Object, com.google.android.gms.common.api.GoogleApiClient$ConnectionCallbacks, com.google.android.gms.common.api.GoogleApiClient$OnConnectionFailedListener)"
08-26 23:16:14.386  3643  3678 E AndroidRuntime: 	at com.google.android.gms.common.api.GoogleApiClient$Builder.build(Unknown Source)
08-26 23:16:14.386  3643  3678 E AndroidRuntime: 	at com.arttitude360.reactnative.rngoogleplaces.RNGooglePlacesModule.buildGoogleApiClient(RNGooglePlacesModule.java:76)
08-26 23:16:14.386  3643  3678 E AndroidRuntime: 	at com.arttitude360.reactnative.rngoogleplaces.RNGooglePlacesModule.<init>(RNGooglePlacesModule.java:59)
08-26 23:16:14.386  3643  3678 E AndroidRuntime: 	at com.arttitude360.reactnative.rngoogleplaces.RNGooglePlacesPackage.createNativeModules(RNGooglePlacesPackage.java:29)
08-26 23:16:14.386  3643  3678 E AndroidRuntime: 	at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:106)
08-26 23:16:14.386  3643  3678 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1009)
08-26 23:16:14.386  3643  3678 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:944)
08-26 23:16:14.386  3643  3678 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.access$600(ReactInstanceManager.java:109)
08-26 23:16:14.386  3643  3678 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager$4.run(ReactInstanceManager.java:743)
08-26 23:16:14.386  3643  3678 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:818)
08-26 23:16:14.387  1624  1635 W ActivityManager:   Force finishing activity com.adventurer/.MainActivity
08-26 23:16:14.395  1259  1315 D gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 1327104
08-26 23:16:14.407  1259  1259 E EGL_emulation: tid 1259: eglCreateSyncKHR(1881): error 0x3004 (EGL_BAD_ATTRIBUTE)
08-26 23:16:14.431  3643  3643 W unknown:React: Packager connection already open, nooping.
08-26 23:16:14.431  3643  3643 W unknown:React: Inspector connection already open, nooping.
08-26 23:16:14.447  1624  3205 I OpenGLRenderer: Initialized EGL, version 1.4
08-26 23:16:14.450  1624  3205 D EGL_emulation: eglCreateContext: 0x9acb8580: maj 2 min 0 rcv 2
08-26 23:16:14.460  1624  3205 D EGL_emulation: eglMakeCurrent: 0x9acb8580: ver 2 0 (tinfo 0x9d9bf7a0)
08-26 23:16:14.473  1624  2023 I AccountManagerService: getTypesVisibleToCaller: isPermitted? true
08-26 23:16:14.478  1624  3205 D EGL_emulation: eglMakeCurrent: 0x9acb8580: ver 2 0 (tinfo 0x9d9bf7a0)
08-26 23:16:14.483  3643  3667 D         : HostConnection::get() New Host Connection established 0xa093f7c0, tid 3667
08-26 23:16:14.526  3643  3667 W         : Unrecognized GLES max version string in extensions: ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_dma_v1
08-26 23:16:14.527  3643  3667 I OpenGLRenderer: Initialized EGL, version 1.4
08-26 23:16:14.528  3643  3667 W OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
08-26 23:16:14.530  3643  3667 D EGL_emulation: eglCreateContext: 0xaa3c8cc0: maj 2 min 0 rcv 2
08-26 23:16:14.537  3643  3667 D EGL_emulation: eglMakeCurrent: 0xaa3c8cc0: ver 2 0 (tinfo 0xb2a62810)
08-26 23:16:14.554  3643  3667 D EGL_emulation: eglMakeCurrent: 0xaa3c8cc0: ver 2 0 (tinfo 0xb2a62810)
08-26 23:16:14.615  3643  3667 D EGL_emulation: eglMakeCurrent: 0xaa3c8cc0: ver 2 0 (tinfo 0xb2a62810)
08-26 23:16:14.628  1624  2021 W InputMethodManagerService: Focus gain on non-focused client com.android.internal.view.IInputMethodClient$Stub$Proxy@4833443 (uid=10060 pid=3643)
08-26 23:16:14.648  3643  3667 D EGL_emulation: eglMakeCurrent: 0xaa3c8cc0: ver 2 0 (tinfo 0xb2a62810)
08-26 23:16:14.690  1995  2147 D EGL_emulation: eglMakeCurrent: 0xae3d45a0: ver 2 0 (tinfo 0xae3d26a0)
08-26 23:16:14.691  3643  3667 D EGL_emulation: eglMakeCurrent: 0xaa3c8cc0: ver 2 0 (tinfo 0xb2a62810)
08-26 23:16:14.780  3643  3667 D EGL_emulation: eglMakeCurrent: 0xaa3c8cc0: ver 2 0 (tinfo 0xb2a62810)
08-26 23:16:14.781  3643  3667 E Surface : getSlotFromBufferLocked: unknown buffer: 0xb403d340
08-26 23:16:14.798  3643  3643 E WindowManager:
08-26 23:16:14.798  3643  3643 E WindowManager: android.view.WindowLeaked: Activity com.adventurer.MainActivity has leaked window com.android.internal.policy.PhoneWindow$DecorView{f10aab5 V.E...... R....... 0,0-1080,1920} that was originally added here
08-26 23:16:14.798  3643  3643 E WindowManager: 	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:368)
08-26 23:16:14.798  3643  3643 E WindowManager: 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:299)
08-26 23:16:14.798  3643  3643 E WindowManager: 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
08-26 23:16:14.798  3643  3643 E WindowManager: 	at android.app.Dialog.show(Dialog.java:319)
08-26 23:16:14.798  3643  3643 E WindowManager: 	at com.cboy.rn.splashscreen.SplashScreen$1.run(SplashScreen.java:34)
08-26 23:16:14.798  3643  3643 E WindowManager: 	at android.app.Activity.runOnUiThread(Activity.java:5511)
08-26 23:16:14.798  3643  3643 E WindowManager: 	at com.cboy.rn.splashscreen.SplashScreen.show(SplashScreen.java:24)
08-26 23:16:14.798  3643  3643 E WindowManager: 	at com.cboy.rn.splashscreen.SplashScreen.show(SplashScreen.java:44)
08-26 23:16:14.798  3643  3643 E WindowManager: 	at com.adventurer.MainActivity.onCreate(MainActivity.java:12)
08-26 23:16:14.798  3643  3643 E WindowManager: 	at android.app.Activity.performCreate(Activity.java:6237)
08-26 23:16:14.798  3643  3643 E WindowManager: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
08-26 23:16:14.798  3643  3643 E WindowManager: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
08-26 23:16:14.798  3643  3643 E WindowManager: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
08-26 23:16:14.798  3643  3643 E WindowManager: 	at android.app.ActivityThread.-wrap11(ActivityThread.java)
08-26 23:16:14.798  3643  3643 E WindowManager: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
08-26 23:16:14.798  3643  3643 E WindowManager: 	at android.os.Handler.dispatchMessage(Handler.java:102)
08-26 23:16:14.798  3643  3643 E WindowManager: 	at android.os.Looper.loop(Looper.java:148)
08-26 23:16:14.798  3643  3643 E WindowManager: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
08-26 23:16:14.798  3643  3643 E WindowManager: 	at java.lang.reflect.Method.invoke(Native Method)
08-26 23:16:14.798  3643  3643 E WindowManager: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
08-26 23:16:14.798  3643  3643 E WindowManager: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
08-26 23:16:14.802  3643  3667 E Surface : getSlotFromBufferLocked: unknown buffer: 0xb403d200
08-26 23:16:17.230  1351  1686 W audio_hw_generic: Not supplying enough data to HAL, expected position 1155090 , only wrote 1017940
```

Do you have any idea of how I could fix this ?

**Comment by jdrouet** [comment]
Just fixed by fixing the version for the services

```

dependencies {
    compile project(':bugsnag-react-native')
    compile project(':react-native-onesignal')
    compile project(':react-native-image-picker')
    compile project(':react-native-fbsdk')
    compile project(':react-native-splash-screen')
    compile project(':react-native-linear-gradient')
    compile(project(':react-native-google-places')){
        exclude group: 'com.google.android.gms', module: 'play-services-base'
        exclude group: 'com.google.android.gms', module: 'play-services-places'
        exclude group: 'com.google.android.gms', module: 'play-services-location'
    }
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"  // From node_modules
    compile "com.google.android.gms:play-services-base:11.+"
    compile 'com.google.android.gms:play-services-places:11.+'
    compile 'com.google.android.gms:play-services-location:11.+'
}
```

**Comment by RecaMedia** [comment]
I know this is already closed but just in case anyone would like to see how this looks with implementation.

```
implementation (project(':react-native-google-places')) {
        exclude group: 'com.google.android.gms', module: 'play-services-base'
        exclude group: 'com.google.android.gms', module: 'play-services-places'
        exclude group: 'com.google.android.gms', module: 'play-services-location'
 }
```
