### ISSUE TITLE
Getting error on Android

### ISSUE THREAD

**Issue by gabrielvcbessa** [tolu360/react-native-google-places#90]
After trying to install this plugin on Android, im getting this error: 

> E/AndroidRuntime: FATAL EXCEPTION: Thread-5
                  Process: com.ufrilla, PID: 26156
                  java.lang.AbstractMethodError: abstract method "com.google.android.gms.common.api.Api$zze com.google.android.gms.common.api.Api$zza.zza(android.content.Context, android.os.Looper, com.google.android.gms.common.internal.zzq, java.lang.Object, com.google.android.gms.common.api.GoogleApiClient$ConnectionCallbacks, com.google.android.gms.common.api.GoogleApiClient$OnConnectionFailedListener)"
                      at com.google.android.gms.common.api.GoogleApiClient$Builder.build(Unknown Source)
                      at com.arttitude360.reactnative.rngoogleplaces.RNGooglePlacesModule.buildGoogleApiClient(RNGooglePlacesModule.java:76)
                      at com.arttitude360.reactnative.rngoogleplaces.RNGooglePlacesModule.<init>(RNGooglePlacesModule.java:59)
                      at com.arttitude360.reactnative.rngoogleplaces.RNGooglePlacesPackage.createNativeModules(RNGooglePlacesPackage.java:29)
                      at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:106)
                      at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1050)
                      at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1021)
                      at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:959)
                      at com.facebook.react.ReactInstanceManager.access$600(ReactInstanceManager.java:109)
                      at com.facebook.react.ReactInstanceManager$4.run(ReactInstanceManager.java:802)
                      at java.lang.Thread.run(Thread.java:762)

**Comment by juergengunz** [comment]
same issue for me but #80 is not helping in my case

**Comment by tolu360** [comment]
Hi @gabrielvcbessa, is this still an issue? If it is, then this one is generally caused by a conflict of GooglePlay Services versions in your app. Can you list what other packages you are using in your project?
